/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToe;

import javax.swing.JFrame;

/**
 * Tic Tac Toe Jan 26, 2018 Jessica Zheng A game called Tic Tac Toe allowing
 * people to play against another person or playing modes against the computer
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        twoPlayerBttn = new javax.swing.JButton();
        fourMode = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        rulesBttn = new javax.swing.JButton();
        unbeatable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(834, 604));

        title.setFont(new java.awt.Font("Sitka Text", 1, 60)); // NOI18N
        title.setText("Tic Tac Toe");

        easy.setBackground(new java.awt.Color(204, 204, 255));
        easy.setFont(new java.awt.Font("Sitka Text", 0, 45)); // NOI18N
        easy.setText("Easy");
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });

        medium.setBackground(new java.awt.Color(204, 204, 255));
        medium.setFont(new java.awt.Font("Sitka Text", 0, 45)); // NOI18N
        medium.setText("Medium");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });

        twoPlayerBttn.setBackground(new java.awt.Color(204, 204, 255));
        twoPlayerBttn.setFont(new java.awt.Font("Sitka Small", 0, 45)); // NOI18N
        twoPlayerBttn.setText("Two-Player");
        twoPlayerBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayerBttnActionPerformed(evt);
            }
        });

        fourMode.setBackground(new java.awt.Color(204, 204, 255));
        fourMode.setFont(new java.awt.Font("Sitka Text", 0, 40)); // NOI18N
        fourMode.setText("Four by Four");
        fourMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourModeActionPerformed(evt);
            }
        });

        hard.setBackground(new java.awt.Color(204, 204, 255));
        hard.setFont(new java.awt.Font("Sitka Text", 0, 45)); // NOI18N
        hard.setText("Hard");
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });

        rulesBttn.setBackground(new java.awt.Color(204, 204, 255));
        rulesBttn.setFont(new java.awt.Font("Sitka Small", 0, 45)); // NOI18N
        rulesBttn.setText("Rules");
        rulesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBttnActionPerformed(evt);
            }
        });

        unbeatable.setBackground(new java.awt.Color(204, 204, 255));
        unbeatable.setFont(new java.awt.Font("Sitka Small", 0, 45)); // NOI18N
        unbeatable.setText("Unbeatable");
        unbeatable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbeatableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medium, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unbeatable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rulesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoPlayerBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourMode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(medium, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(unbeatable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(hard, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(rulesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(twoPlayerBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(fourMode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        //closes current frame and opens the easy frame
        JFrame aiEasy = new aiEasy();
        aiEasy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_easyActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        //closes current frame and opens the medium frame
        JFrame aiMedium = new aiMedium();
        aiMedium.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mediumActionPerformed

    private void twoPlayerBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayerBttnActionPerformed
        //closes current frame and opens the two player frame
        JFrame play = new twoPlayer();
        play.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_twoPlayerBttnActionPerformed

    private void fourModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourModeActionPerformed
        //closes current frame and opens the four by four two player frame
        JFrame fourByFour = new fourByFour();
        fourByFour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fourModeActionPerformed

    private void rulesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBttnActionPerformed
        //closes current frame and opens the rules frame
        JFrame rules = new rules();
        rules.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rulesBttnActionPerformed

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
        //closes current frame and opens the hard frame
        JFrame aiHard = new aiHard();
        aiHard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hardActionPerformed

    private void unbeatableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbeatableActionPerformed
        //closes current frame and opens the unbeatable frame
        JFrame aiUnbeatable = new aiUnbeatable();
        aiUnbeatable.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_unbeatableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easy;
    private javax.swing.JButton fourMode;
    private javax.swing.JButton hard;
    private javax.swing.JButton medium;
    private javax.swing.JButton rulesBttn;
    private javax.swing.JLabel title;
    private javax.swing.JButton twoPlayerBttn;
    private javax.swing.JButton unbeatable;
    // End of variables declaration//GEN-END:variables
}
